// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
/// options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return web;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO4tj--efEhryWAXkNwXXnZbLGyY_ZjFA',
    appId: '1:631074193956:web:e95076f24598105c350eb1',
    messagingSenderId: '631074193956',
    projectId: 'vs6451071057',
    authDomain: 'vs6451071057.firebaseapp.com',
    storageBucket: 'vs6451071057.firebasestorage.app',
    measurementId: 'G-7DZ707184Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5DOHyELN5t-376lmot8BQHJvIrQG8sJs',
    appId: '1:631074193956:android:4b4110070889795a350eb1',
    messagingSenderId: '631074193956',
    projectId: 'vs6451071057',
    storageBucket: 'vs6451071057.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpj8n-wsLYf3UMgj-LS1lHwu_HcSX5KOw',
    appId: '1:631074193956:ios:c77a7df504b78ec7350eb1',
    messagingSenderId: '631074193956',
    projectId: 'vs6451071057',
    storageBucket: 'vs6451071057.firebasestorage.app',
    iosBundleId: 'com.example.thuchanh',
  );
}
