// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
/// options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtQyzvaXcahnluQcUA-SfLfQa4I_BelVU',
    appId: '1:233797330677:web:1144538c1e2448281547bc',
    messagingSenderId: '233797330677',
    projectId: 'map-lab-utc2-e-commerce',
    authDomain: 'map-lab-utc2-e-commerce.firebaseapp.com',
    databaseURL: 'https://map-lab-utc2-e-commerce-defaultrtdb.firebaseio.com',
    storageBucket: 'map-lab-utc2-e-commerce.firebasestorage.app',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0QeNGSqyEFdGnBA7RGj1eX7eg8DszWCw',
    appId: '1:233797330677:android:7a2085ef1aae5efd1547bc',
    messagingSenderId: '233797330677',
    projectId: 'map-lab-utc2-e-commerce',
    databaseURL: 'https://map-lab-utc2-e-commerce-defaultrtdb.firebaseio.com',
    storageBucket: 'map-lab-utc2-e-commerce.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXZUSrEE1I3At-sYipZmJ61BDYlEVVGA0',
    appId: '1:233797330677:ios:f64bcee6160714301547bc',
    messagingSenderId: '233797330677',
    projectId: 'map-lab-utc2-e-commerce',
    databaseURL: 'https://map-lab-utc2-e-commerce-defaultrtdb.firebaseio.com',
    storageBucket: 'map-lab-utc2-e-commerce.firebasestorage.app',
    iosBundleId: 'com.example.drafProjectWeb',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXZUSrEE1I3At-sYipZmJ61BDYlEVVGA0',
    appId: '1:233797330677:ios:f64bcee6160714301547bc',
    messagingSenderId: '233797330677',
    projectId: 'map-lab-utc2-e-commerce',
    databaseURL: 'https://map-lab-utc2-e-commerce-defaultrtdb.firebaseio.com',
    storageBucket: 'map-lab-utc2-e-commerce.firebasestorage.app',
    iosBundleId: 'com.example.drafProjectWeb',
  );
}
